---
- name: Atualização dos Sudoers
  hosts: all
  become: yes
  gather_facts: no

  tasks:
    - name: Backup do Sudoers
      ansible.builtin.copy:
        src: /etc/sudoers
        dest: /etc/sudoers.bkp
        owner: root
        group: root
        mode: '0440'
        remote_src: yes
      become: yes

    - name: Copia o arquivo atualizado.
      ansible.builtin.copy:
        src: file/srv-k3s/sudoers  # Caminho para o seu arquivo sudoers local
        dest: /etc/sudoers.new
        owner: root
        group: root
        mode: '0440'
      become: yes

    - name: Valida o novo arquivo sudoers
      ansible.builtin.command:
        cmd: visudo -cf /etc/sudoers.new
      register: validation_result
      become: yes
      ignore_errors: true

    - name: Renomeia o arquivo sudoers.new se for válido
      ansible.builtin.command:
        cmd: mv /etc/sudoers.new /etc/sudoers
      when: validation_result.rc == 0
      become: yes

    - name: Exibe erros de validação
      ansible.builtin.debug:
        msg: "{{ validation_result.stderr }}"
      when: validation_result.rc != 0

